// This file is auto-generated by Lovable. Do not modify it.
// MIGRATION: this is the ONE file that wraps a Lovable-proprietary package
// (@lovable.dev/cloud-auth-js) purely for social OAuth sign-in (Google/Apple/
// Microsoft). Email/password auth already goes through plain
// @supabase/supabase-js (see client.ts) and needs NO changes. Replace this
// file's signInWithOAuth with supabase.auth.signInWithOAuth({ provider, options })
// directly — standard Supabase OAuth, no Lovable dependency needed.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
